### ISSUE TITLE
バックエンド環境構築する

### ISSUE THREAD

**Issue by kakeru-one** [ochi-sho-private-study/muscle-dev#1]

**Comment by ochi-sho-private-study** [comment]
👍

**Comment by kakeru-one** [comment]
## Dockerfile
```dockerfile
FROM ruby:3.3.4-bullseye

WORKDIR /usr/src/app

ENV LANG C.UTF-8
ENV TZ Asia/Tokyo

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        git \
        libmariadb-dev-compat \
        mariadb-client \
        less \
        vim && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY ../Gemfile ../Gemfile.lock ./
RUN bundle install
```

## docker-compose.yml
```yml
version: "3"

services:
  backend:
    container_name: en-match-backend
    build:
      context: ../
      dockerfile: ./infra/Dockerfile.dev
    volumes:
      - ../:/usr/src/app
    stdin_open: true
    tty: true
    env_file:
      - ./backend.env
    ports:
      - 3300:3000
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: en-match-database
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
volumes:
  db-data:
    driver: local
```

## backend.env
```
DATABASE_URL=mysql2://root:root@db/app_development
DATABASE_TEST_URL=mysql2://root:root@db/app_test
```
